// scripts/install/ecosystem.config.js
module.exports = {
  apps: [
    {
      name: 'ku-api',
      cwd: '/opt/ku_wave_plat/apps/api',
      script: 'dist/main.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 8000,
      },
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      max_memory_restart: '512M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/opt/ku_wave_plat/logs/api-error.log',
      out_file: '/opt/ku_wave_plat/logs/api-out.log',
      merge_logs: true,
    },
    {
      name: 'ku-console',
      cwd: '/opt/ku_wave_plat/apps/console',
      script: 'node_modules/.bin/next',
      args: 'start -p 3000',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      max_memory_restart: '512M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/opt/ku_wave_plat/logs/console-error.log',
      out_file: '/opt/ku_wave_plat/logs/console-out.log',
      merge_logs: true,
    },
    {
      name: 'ku-nfc',
      cwd: '/opt/ku_wave_plat/apps/nfc',
      script: 'dist/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
      },
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      max_memory_restart: '256M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      error_file: '/opt/ku_wave_plat/logs/nfc-error.log',
      out_file: '/opt/ku_wave_plat/logs/nfc-out.log',
      merge_logs: true,
    },
  ],
};
